blog/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index_url'),
    path('create/', views.new_post, name='new_post_url'),
]
                                     

blog/models.py
from django.db import models


class Post(models.Model):
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250)
    text = models.TextField()
    image = models.ImageField(upload_to='upload_images', blank=True)
    publish = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, redirect
from .models import Post
from .forms import PostAddForm

def index(request):
    last_post = Post.objects.all()[:1]
    posts = Post.objects.all()[1:10]
    return render(request,
	          'blog/index.html',
              {'last_post' : last_post,
	          'posts': posts})

def new_post(request):
    form = PostAddForm()
    if request.method == 'POST':
        form = PostAddForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('/blog')
    return render(request, 'blog/new_post.html', context={'form': form})

blog/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Kodland Blog</title>
    <link rel="stylesheet" href="{% static 'blog/css/index.css' %}">
</head>
<body>
<div class="kodland-navbar">
        <div class="row margin-bottom-remove">
            <div class="col s2 kodland-logo">
                <img class="responsive-img" src="{% static 'blog/images/logo_kodland.png' %}" alt="Kodland">
            </div>
            <div class="col s8 kodland-breadcrumbs">
                {% block breadcrumbs %}{% endblock %}
            </div>
            <div class="col s2 kodland-actions">
                <img src="{% static 'blog/images/email.svg' %}" alt="Messages">
                <img src="{% static 'blog/images/profile.png' %}" alt="Profile">
                <img src="{% static 'blog/images/logout.svg' %}" alt="Logout">
            </div>
        </div>
    </div>
    <div class="divider"></div>
    {% block header %}
    {% endblock %}
    {% block content %}
    {% endblock %}
 <script src="{% static 'blog/js/index.js' %}"></script>
</body>
</html>

blog/templates/blog/index.html
{% extends 'base.html' %}
{% load static %}

{% block header %}
    

       <div class="section container">

            <div>
                <div class="row">
                    <div class="col s1">
                        <span class="kodland-badge-new">NEW</span>
                    </div>
                    <div class="col s11">
                        <div class="kodland-counters">
                            <div>
                                 <span>25 <img src="{% static 'blog/images/heart.svg' %}" height="12" alt="Likes"></span>
                            </div>
                            <div>
                               <span>25 <img src="{% static 'blog/images/balloon.svg' %}" height="12" alt="Comments"></span>
                            </div>
                            <div>
                            <span>25 <img src="{% static 'blog/images/eye.svg' %}" height="12" alt="Views"></span>
                            </div>
                        </div>
                    </div>
                </div>
                {% for last_post in last_post %}
                <div class="row">
                    <div class="col s8">
                        <h3 class="margin-top-remove">{{ last_post.title }}</h3>
                        <p>{{ last_post.text|truncatewords:25 }}</p>
                        <a href="#!" class="btn">Читать</a>
                    </div>
                    <div class="col s4">
                        <img class="responsive-img" src="{{ last_post.image }}">
                    </div>
                </div>
                {% endfor %}
            </div>

    </div>
    <div class="divider"></div>

    <div class="section container">
        <div class="row valign-wrapper">
            <div class="col s11">
                <h4>Другие статьи</h4>
            </div>
            <div class="col s1">
                <img src="{% static 'blog/images/filter.svg' %}" alt="Filter">
            </div>
        </div>
        <div class="row">


{% endblock %}



{% block content %}

        <div class="col s4">
                    <div class="card kodland-article-card">
                        <div class="card-image">
                            <div class="kodland-card-date">{{ posts.publish }}</div>
                            <img class="responsive-img"  src="{{ posts.image.url }}">
                        </div>
                        <div class="card-content">
                            <div class="card-title">
                                <h5>{{ posts.title }}</h5>
                            </div>
                        </div>
                        <div class="card-action">
                            <div class="kodland-counters">
                                <div>
                                    <img src="{% static 'blog/images/heart.svg' %}" alt="Likes">
                                    <span>25</span>
                                </div>
                                <div>
                                    <img src="{% static 'blog/images/balloon.svg' %}" alt="Comments">
                                    <span>25</span>
                                </div>
                                <div>
                                    <img src="{% static 'blog/images/eye.svg' %}" alt="Views">
                                    <span>25</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

{% endblock %}

blog/templates/blog/new_post.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

    <div class="container">

        <h5>Добавить статью</h5>

        <form enctype="multipart/form-data" action method="POST" novalidate>

            {% csrf_token %}

            <div class="row">
                <div class="input-field col s7 m7 l7">
                    <input type="text" class="validate" name="title" id="id_title" placeholder="Введите название статьи">
                </div>
                <div class="col s5 m5 l5" type="submit" name="action">
                    <input class="btn" type="submit" value="Опубликовать">
                </div>
            </div>

            <div class="row">
                <div class="input-field col s7 m7 l7">

                    <textarea name="text" id="id_text" style="resize: none; height: 250px;"></textarea>
                </div>
                <div class="col s5 m5 l5">
                    <div class="card-panel center">
                        <h6>Загрузить изображение</h6>
                        <div id="image_label_id">
                            <label for="image_input_id" class="btn">Выберите файл</label>
                        </div>
                        <input type="file" class="input-image" name="image"
                               accept="upload_images/*" id="image_input_id"
                               onchange="showImage(this)">
                    </div>
                </div>
            </div>

            <script>
                function showImage(fileInput) {
                    var files = fileInput.files;
                    if (files.length == 1) {
                        var file = files[0];
                        var imageType = /.*/;
                        if (file.type.match(imageType)) {
                            var container = document.getElementById("image_label_id");
                            container.innerHTML = '<label for="image_input_id"><img id="image_preview" src="" alt="image" width="217" height="112" /></label>';
                            var img = document.getElementById("image_preview");
                            img.file = file;
                            var reader = new FileReader();
                            reader.onload = (function(aImg) {
                                return function(e) {
                                    aImg.src = e.target.result;
                                };
                            })(img);
                            reader.readAsDataURL(file);
                        }
                    }
                }
            </script>

        </form>
    </div>

{% endblock %}